version: "3"
services:
  geoip:
    image: dserranoc/geotraefik
    container_name: geotraefik
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - proxy
    environment:
      - PORT=8000 # Change this if you want to use a different port, don't forget to change it in exposed ports as well.
      - COUNTRIES=
      - ASNS=
      - IPS=
      - LIST_MODE=block # Change this to "allow" or "block" to allow or block the IPs, ASNs, or countries in the list. If set to "allow", only the IPs, ASNs, or countries in the list will be allowed. If set to "block", the IPs, ASNs, or countries in the list will be blocked. If this value is not set, the default value is "block".
    volumes:
      - ./databases:/home/node/app/databases:ro

  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=XXXXXX # Replace with your MaxMind account ID
      - GEOIPUPDATE_LICENSE_KEY=XXXXXXXXXXXXXXXX # Replace with your MaxMind license key
      - "GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country"
      - GEOIPUPDATE_FREQUENCY=72 # Update the databases every 72 hours. Change this if you want to update the databases more or less frequently.
    volumes:
      - "./databases:/usr/share/GeoIP"

networks:
  proxy: # <--- name of the network used by Traefik and this middleware
    external: true